---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-management-deployment
  labels:
    app: book-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-management
  template:
    metadata:
      labels:
        app: book-management
    spec:
      containers:
        - name: book-management
          image: cuongld2/fastapi-service-tekton:latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
            name: docker-secret
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_HOST
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_USERNAME
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_PASSWORD
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_PORT
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_NAME
                  optional: false
