apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr
  namespace: tekton
spec:
  serviceAccountName: tekton-service-account
  triggers:
    - name: pr-trigger
      bindings:
        - ref: github-pr-trigger-binding
      template:
        ref: github-pr-trigger-template