apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-pipelinerun-1
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: tekton-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: IMAGE
      value: cuongld2/fastapi-tekton
    - name: TAG
      value: latest
    - name: repo-url
      value: https://github.com/cuongld2/fastapi-tekton
    - name: revision
      value: main
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi