apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-pipeline
spec:
  params:
    - name: IMAGE
      description: Image description
      type: string
      default: "docker.io/cuongld2/fastapi-tekton"
    - name: TAG
      description: Preferred tag
      default: latest
    - name: repo-url
      type: string
    - name: revision
      type: string
  workspaces:
    - name: linked-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "$(params.revision)"
    - name: run-unit-test
      taskRef:
        name: pytest-task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: PYTHON_IMAGE
          value: "docker.io/python:3.9"
        - name: SOURCE_PATH
          value: "test_unit.py"
    - name: run-integration-test
      taskRef:
        name: pytest-task
      runAfter:
        - run-unit-test
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: PYTHON_IMAGE
          value: "docker.io/python:3.9"
        - name: SOURCE_PATH
          value: "test_integration.py"
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - run-integration-test
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: FORMAT
          value: "docker"
    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-image
      params:
        - name: script
          value: |
            kubectl apply --filename kubernetes/pipeline.yml
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace