apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-pipelinerun-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: tekton-pipeline
  params:
    - name: IMAGE
      value: cuongld2/fastapi-service-tekton
    - name: TAG
      value: latest
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi