apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-pr-trigger-template
  namespace: tekton
spec:
  params:
    - name: revision
      default: main
    - name: repo-url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: tekton-pipelinerun-trigger-
    spec:
      serviceAccountName: docker-login
      pipelineRef:
        name: tekton-pipeline
      podTemplate:
        securityContext:
          fsGroup: 65532
        params:
          - name: IMAGE
            value: cuongld2/fastapi-tekton
          - name: TAG
            value: latest
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: revision
            value: $(tt.params.revision)
        workspaces:
          - name: linked-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi