apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-trigger-binding
  namespace: tekton
spec:
  params:
  - name: revision
    value: main
  - name: repo-url
    value: $(body.repository.clone_url)